charities:
  descriptions:
    Dog4Care: A non-profit organization dedicated to helping homeless dogs find loving and caring families.
    EduPriv: A non-profit organization dedicated to providing education and resources to underprivileged children.
    Green4ever: A non-profit organization committed to environmental conservation and sustainability.