version: '3'

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    hostname: postgres
    container_name: postgres
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres